name: ESLint Check
on:
  push:
    branches: [master, development]
  pull_request:
    branches: [master, development]

jobs:
  lint-files:
    runs-on: ubuntu-latest 
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 'latest'
      - name: Install Packages
        run: npm install
      - name: Lint Files
        run: npm run eslint
